name: Publish code coverage
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: paambaati/codeclimate-action@v9.0.0
        env:
           CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
           with:
           coverageCommand: make test-coverage